### ISSUE TITLE
Build error on CentOS Stream 8

### ISSUE THREAD

**Issue by michel-slm** [facebook/CacheLib#117]
**Describe the bug**
CacheLib fails to build using the official build script

**To Reproduce**
1. Install [distrobox](https://github.com/89luca89/distrobox)
2. Create a CentOS Stream 8 container: `distrobox create --image quay.io/centos/centos:stream8 --name c8s-cachelib`
3. On the host, check out CacheLib. Tested on commit a6882d8e642053caa70d622c9f92a62b3b8947f0 (Feb 24)
4. `distrobox enter c8s-cachelib`
5. On the container, `./contrib/build.sh -d -j -v` per the instructions in `BUILD.md`

**Expected behavior**
This should build

**Logs**
[cachelib-c8s-error.log](https://github.com/facebook/CacheLib/files/8138112/cachelib-c8s-error.log)

**Desktop (please complete the following information):**
 - OS: CentOS Stream 8
```
$ rpm -q centos-stream-release
centos-stream-release-8.6-1.el8.noarch
```

**Additional context**
I tried this to triage the build issue with the latest CacheLib in Fedora. Back in December, this builds fine: https://bodhi.fedoraproject.org/updates/?packages=cachelib but now it fails with the same errors.

**Comment by agordon** [comment]
Thanks for the detailed log @michel-slm , I'm working on a fix.

**Comment by therealgymmy** [comment]
@agordon: this is the diff that broke the build: https://github.com/facebook/CacheLib/commit/c4636eed16b2476ed9c1105297f862e24d4155f8

We had an automated code-mod internally to simplify some fb thrift API calls. It passed builds internally but broke here.

**Comment by agordon** [comment]
The removal of `_ref()` suffix from Thrift-generated files is a recent feature of 'thrift', though it seems the code generated internally differs slightly from the code we get when building fbthrift locally. Main symptom is that thrift objects with fields marked as `required` ( e.g. https://github.com/facebook/CacheLib/blob/main/cachelib/allocator/serialize/objects.thrift#L48 ) still generate only the accessors with the `_ref()` suffix.  This is being investigated...

**Comment by michel-slm** [comment]
Fixed in https://github.com/facebook/fbthrift/commit/44aec7990b140e74d73066092d52a0a25116dc89
