### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by igchor** [facebook/CacheLib#135]
Hi!

I noticed that the CI on main branch and on PRs is failing. Would you be open to integrating CI from our fork (pmem/CacheLib)?

Right now we are building CacheLib and running (almost) all tests on each PR/push on GHA. To speed up things, we are using docker images with pre-installed dependencies. You can see our workflow here: https://github.com/pmem/CacheLib/blob/main/.github/workflows/build-cachelib-docker.yml In our system, we can trigger docker rebuild and push it to the registry once we need to update the dependencies.

**Comment by agordon** [comment]
Thanks, @igchor , I'm investigating this.
