### ISSUE TITLE
Running Error when running the examples

### ISSUE THREAD

**Issue by chuckleLZY** [facebook/CacheLib#147]
I built cachelib in Ubuntu20.04 with 
`./contrib/build.sh -d -j -v` .
Then I built the examples, e.g. simple_cache with command
`./build.sh`
Finally, I ran the example, ` ./build/simple_cache` .

But here has the error message:
`ERROR: flag 'logtostderr' was defined more than once (in files '/data/scott/programs/CacheLib/cachelib/external/glog/src/logging.cc' and 'src/logging.cc').`

How can I fix it?

**Comment by therealgymmy** [comment]
@chuckleLZY: Hi, did you resolve the issue?

**Comment by chuckleLZY** [comment]
> 

yes, I found the same issue in CacheLib, and resolve my problem. Thanks.

**Comment by shkim0413** [comment]
@chuckleLZY  
Hello, I'm Sohyun
I have a same problem. 
how did you solve the issue?

**Comment by wangyuyue** [comment]
It seems that #51 is a solution.
