### ISSUE TITLE
fail to build wangle on Ubuntu 18.04

### ISSUE THREAD

**Issue by Dingcui-Yu** [facebook/CacheLib#156]
I have built `folly` and `fbthrift` on my system before. Then I try to build cachelib using `./contrib/build.sh -j -T`  , and when trying to build `wangle`, it failed. These are the message shown on my terminal:

> Scanning dependencies of target wangle
[  3%] Building CXX object CMakeFiles/wangle.dir/acceptor/TransportInfo.cpp.o
[  6%] Building CXX object CMakeFiles/wangle.dir/acceptor/TLSPlaintextPeekingCallback.cpp.o
[ 12%] Building CXX object CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o
[ 12%] Building CXX object CMakeFiles/wangle.dir/acceptor/AcceptorHandshakeManager.cpp.o
[ 15%] Building CXX object CMakeFiles/wangle.dir/acceptor/EvbHandshakeHelper.cpp.o
[ 18%] Building CXX object CMakeFiles/wangle.dir/acceptor/ConnectionManager.cpp.o
[ 21%] Building CXX object CMakeFiles/wangle.dir/acceptor/FizzAcceptorHandshakeHelper.cpp.o
[ 24%] Building CXX object CMakeFiles/wangle.dir/acceptor/LoadShedConfiguration.cpp.o
[ 27%] Building CXX object CMakeFiles/wangle.dir/acceptor/FizzConfigUtil.cpp.o
[ 30%] Building CXX object CMakeFiles/wangle.dir/acceptor/SocketOptions.cpp.o
[ 36%] Building CXX object CMakeFiles/wangle.dir/acceptor/ManagedConnection.cpp.o
[ 36%] Building CXX object CMakeFiles/wangle.dir/acceptor/SecureTransportType.cpp.o
[ 39%] Building CXX object CMakeFiles/wangle.dir/ssl/TLSCredProcessor.cpp.o
[ 42%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLUtil.cpp.o
[ 45%] Building CXX object CMakeFiles/wangle.dir/bootstrap/ServerBootstrap.cpp.o
[ 48%] Building CXX object CMakeFiles/wangle.dir/acceptor/SSLAcceptorHandshakeHelper.cpp.o
[ 51%] Building CXX object CMakeFiles/wangle.dir/channel/FileRegion.cpp.o
[ 54%] Building CXX object CMakeFiles/wangle.dir/client/persistence/FilePersistenceLayer.cpp.o
[ 57%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldBasedFrameDecoder.cpp.o
[ 60%] Building CXX object CMakeFiles/wangle.dir/channel/Pipeline.cpp.o
[ 66%] Building CXX object CMakeFiles/wangle.dir/ssl/PasswordInFileFactory.cpp.o
[ 66%] Building CXX object CMakeFiles/wangle.dir/util/FilePoller.cpp.o
[ 69%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLContextManager.cpp.o
[ 72%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldPrepender.cpp.o
[ 75%] Building CXX object CMakeFiles/wangle.dir/client/ssl/SSLSessionCacheData.cpp.o
[ 78%] Building CXX object CMakeFiles/wangle.dir/ssl/SSLSessionCacheManager.cpp.o
[ 84%] Building CXX object CMakeFiles/wangle.dir/client/persistence/PersistentCacheCommon.cpp.o
[ 84%] Building CXX object CMakeFiles/wangle.dir/client/ssl/SSLSessionCacheUtils.cpp.o
[ 87%] Building CXX object CMakeFiles/wangle.dir/client/ssl/SSLSessionCallbacks.cpp.o
[ 90%] Building CXX object CMakeFiles/wangle.dir/ssl/ServerSSLContext.cpp.o
[ 96%] Building CXX object CMakeFiles/wangle.dir/ssl/TLSTicketKeyManager.cpp.o
[ 96%] Building CXX object CMakeFiles/wangle.dir/codec/LineBasedFrameDecoder.cpp.o
/home/lab/CacheLib/cachelib/external/wangle/wangle/ssl/SSLSessionCacheManager.cpp:44:25: error: expected constructor, destructor, or type conversion before ‘(’ token
 FOLLY_GFLAGS_DEFINE_bool(
                         ^
/home/lab/CacheLib/cachelib/external/wangle/wangle/ssl/SSLSessionCacheManager.cpp: In constructor ‘wangle::SSLSessionCacheManager::SSLSessionCacheManager(uint32_t, uint32_t, folly::SSLContext*, const string&, wangle::SSLStats*, const std::shared_ptr<wangle::SSLCacheProvider>&)’:
/home/lab/CacheLib/cachelib/external/wangle/wangle/ssl/SSLSessionCacheManager.cpp:172:8: error: ‘FLAGS_dcache_unit_test’ was not declared in this scope
   if (!FLAGS_dcache_unit_test && !context.empty()) {
        ^~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/wangle.dir/build.make:710: recipe for target 'CMakeFiles/wangle.dir/ssl/SSLSessionCacheManager.cpp.o' failed
make[2]: *** [CMakeFiles/wangle.dir/ssl/SSLSessionCacheManager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/wangle.dir/all' failed
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
build-package.sh: error: make failed
build.sh: error: failed to build dependency 'wangle'

I tried to build `wangle` manually and ran `cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/lab/CacheLib/opt/cachelib/ ../cachelib/external/wangle/wangle`.

Then it showed some warning message like these:

> CMake Warning at CMakeLists.txt:139 (add_library):
  Cannot generate a safe runtime search path for target wangle because files
  in some directories may conflict with libraries in implicit directories:
    runtime library [libglog.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/lab/CacheLib/opt/cachelib/lib
    runtime library [libgflags.so.2.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/lab/CacheLib/opt/cachelib/lib
  Some of these libraries may not be found correctly.
...

Then I ran `make -j39`, I got the same error message as running `./contrib/build.sh -j -T`.

Can anyone tell me how to address this problem? Thank you very much!

**Comment by therealgymmy** [comment]
@Dingcui-Yu: hi did you fix your issue? Mind clarifying what you did?

**Comment by Dingcui-Yu** [comment]
Yes. I just find the installation path of my folly and fbthrift and delete the related files.  Then I redo every thing and it works well.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 08/23/2022 02:19 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [facebook/CacheLib] fail to build wangle on Ubuntu 18.04 (Issue #156) |

@Dingcui-Yu: hi did you fix your issue? Mind clarifying what you did?
