### ISSUE TITLE
can cachelib be built and run on windows?

### ISSUE THREAD

**Issue by DongZhaoYu** [facebook/CacheLib#160]
I wonder if cachelib can run on windows system. If not, is there any block to port it to windows?

**Comment by agordon** [comment]
Hello @DongZhaoYu , 
While I don't think this has been ever tested, I would recommend trying first by building cachelib inside WSL (Window's Subsystem for Linux) - that would give an environment similar enough to linux to start building.

To build natively on windows (e.g. with MSVC), I see two big hurdles:
1. Getting all the dependencies to work, particularly Folly and FBThrift libraries.
2. Few elements in Cachelib are very unix-specific (e.g. shared memory calls). This could be adapted to windows, but I'm not sure what would be the complexity of that.
