### ISSUE TITLE
How easy it is to to modify CacheLib as a simulator to only measure miss ratio?

### ISSUE THREAD

**Issue by sunnyszy** [facebook/CacheLib#202]
Hello,

I'm working on a cache configuration project. As an intermediate step, I'm thinking of modifying CacheLib as a simulator only to measure the miss ratio. This would allow me to run a large number of CacheLib experiments assuming each one has a low memory overhead.

To do this, I know how to modify the nvm cache but have no idea on the memory cache. Therefore I would like to know whether it is easy to hack the memory cache into a simulator mode. To be specific, this would mean disabling the actual memory allocation and data transfer.

**Comment by wonglkd** [comment]
Hi Zhenyu, how much fidelity to CacheLib do you need? By cache configuration, do you mean admission & eviction policies? Things like cache sizes & target write rates (for NVM)? Are you looking for a cache simulator to do exploration before you do actual CacheLib experiments, or do you actually want/need to retain CacheLib's specific characteristics and just 'hollow out' CacheLib by disabling the expensive bits?

(Speaking as a fellow PhD student who does simulation of CacheLib for admission policies)

**Comment by sunnyszy** [comment]
Hi @wonglkd ,

Thanks for the follow-up. 

- The end goal of my project is to evaluate how well CacheLib runs with a specific configuration on real hardware. 
- The cache configuration is about an edge cluster, including the number of nodes and hardware/software on each node. For example, one software configuration is the chunk size in the PieceWise cache of cachebench. 
- As a simulator is an intermediate step, it is okay to have low fidelity. However, if it is possible I would like to retain CacheLib's specific characteristics and just 'hollow out' CacheLib by disabling the expensive bits. This path would save a lot of engineering effort for me to write a separate simulator.

**Comment by jaesoo-fb** [comment]
Hi @sunnyszy (thanks @wonglkd for clarifying questions),

**Comment by sunnyszy** [comment]
Thank you. This is very clear.
