### ISSUE TITLE
"Get started" link on cachelib.org front page is broken

### ISSUE THREAD

**Issue by wonglkd** [facebook/CacheLib#204]
Links to https://cachelib.org/docs/installation/installation, which doesn't exist. https://cachelib.org/docs/installation does exist. The same link is broken in README.md as well.

**Comment by jaesoo-fb** [comment]
Thanks for reporting this issue. Just fixed.

**Comment by wonglkd** [comment]
I hope I'm just viewing an outdated and cached version but... the links still seem broken for me? Sorry!

![image](https://user-images.githubusercontent.com/2821951/222654250-444e56b8-0fb5-4378-9fd2-3c1f4c90dece.png)

https://github.com/facebook/CacheLib/blob/185bbe6664167a680f4070713987548573cbbd2c/website/src/pages/index.js#L120

![image](https://user-images.githubusercontent.com/2821951/222654329-86858da9-b184-4190-8f19-805093918c62.png)


https://github.com/facebook/CacheLib/blob/185bbe6664167a680f4070713987548573cbbd2c/README.md?plain=1#L53

**Comment by jaesoo-fb** [comment]
Oh, sorry, I think I missed another one in `index.js`; I will soon upload the change. The other one in `README.md` had been fixed; we will see the update as soon as the commit is synced to github from Meta internal.

**Comment by jaesoo-fb** [comment]
fixed
