### ISSUE TITLE
error occurres when building in ubuntu22.04&20.04

### ISSUE THREAD

**Issue by hyperjlord** [facebook/CacheLib#243]
A few days ago i still can build CacheLib normally, but today when I built it as what README said, I always met an error which is like:

```
/usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/BogoShim.dir/build.make:125: bin/fizz-bogoshim] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/BogoShim.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/FizzTool.dir/build.make:221: bin/fizz] Error 1
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/FizzTool.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
build-package.sh: error: make failed
build.sh: error: failed to build dependency 'fizz'
``` 
I met the same error both in Ubuntu 22.04 and Ubuntu 20.04.,and  It seems that the building workflow in this repo also failed because of the same reason. Is there any solution?

**Comment by zhyq0520** [comment]
i see this problem too. 
fizz of tag v2023.06.08.00 is ok
it seems that fizz add some features

**Comment by zhyq0520** [comment]
![image](https://github.com/facebook/CacheLib/assets/8245175/39c3c47a-e506-4e16-8a52-841659accb90)
![image](https://github.com/facebook/CacheLib/assets/8245175/2ab2139b-911f-4cda-bb47-33dab87709d8)

**Comment by zhyq0520** [comment]
> A few days ago i still can build CacheLib normally, but today when I built it as what README said, I always met an error which is like:
> 
> ```
> /usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/BogoShim.dir/build.make:125: bin/fizz-bogoshim] Error 1
> make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/BogoShim.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> /usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/FizzTool.dir/build.make:221: bin/fizz] Error 1
> make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/FizzTool.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2
> build-package.sh: error: make failed
> build.sh: error: failed to build dependency 'fizz'
> ```
> 
> I met the same error both in Ubuntu 22.04 and Ubuntu 20.04.,and It seems that the building workflow in this repo also failed because of the same reason. Is there any solution?

one way to workaroud it to modify contrib/update-submodules.sh  by setting git checkout --force "v2023.06.08.00" in the fbthrift part

**Comment by jaesoo-fb** [comment]
@zhyq0520 Thanks for providing the workaround. 

FYI, the following fix in `fizz` had been submitted a day ago, but it could take some time to be propagated to `cachelib`.
```
diff --git a/fizz/CMakeLists.txt b/fizz/CMakeLists.txt
index e0ffc90a..e594289f 100644
--- a/fizz/CMakeLists.txt
+++ b/fizz/CMakeLists.txt
@@ -233,6 +233,7 @@ set(FIZZ_SOURCES
   third-party/libsodium-aegis/aegis256/aesni/aead_aegis256_aesni.c
   third-party/libsodium-aegis/aegis256/armcrypto/aead_aegis256_armcrypto.c
   third-party/libsodium-aegis/aegis256/soft/aead_aegis256_soft.c
+  third-party/libsodium-aegis/private/softaes.c
 )
```

**Comment by hyperjlord** [comment]
> > A few days ago i still can build CacheLib normally, but today when I built it as what README said, I always met an error which is like:
> > ```
> > /usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
> > collect2: error: ld returned 1 exit status
> > make[2]: *** [CMakeFiles/BogoShim.dir/build.make:125: bin/fizz-bogoshim] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/BogoShim.dir/all] Error 2
> > make[1]: *** Waiting for unfinished jobs....
> > /usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
> > collect2: error: ld returned 1 exit status
> > make[2]: *** [CMakeFiles/FizzTool.dir/build.make:221: bin/fizz] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/FizzTool.dir/all] Error 2
> > make: *** [Makefile:156: all] Error 2
> > build-package.sh: error: make failed
> > build.sh: error: failed to build dependency 'fizz'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I met the same error both in Ubuntu 22.04 and Ubuntu 20.04.,and It seems that the building workflow in this repo also failed because of the same reason. Is there any solution?
> 
> one way to workaroud it to modify contrib/update-submodules.sh by setting git checkout --force "v2023.06.08.00" in the fbthrift part

Thank you for your help, It does work for me.

> > A few days ago i still can build CacheLib normally, but today when I built it as what README said, I always met an error which is like:
> > ```
> > /usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
> > collect2: error: ld returned 1 exit status
> > make[2]: *** [CMakeFiles/BogoShim.dir/build.make:125: bin/fizz-bogoshim] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/BogoShim.dir/all] Error 2
> > make[1]: *** Waiting for unfinished jobs....
> > /usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
> > collect2: error: ld returned 1 exit status
> > make[2]: *** [CMakeFiles/FizzTool.dir/build.make:221: bin/fizz] Error 1
> > make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/FizzTool.dir/all] Error 2
> > make: *** [Makefile:156: all] Error 2
> > build-package.sh: error: make failed
> > build.sh: error: failed to build dependency 'fizz'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I met the same error both in Ubuntu 22.04 and Ubuntu 20.04.,and It seems that the building workflow in this repo also failed because of the same reason. Is there any solution?
> 
> one way to workaroud it to modify contrib/update-submodules.sh by setting git checkout --force "v2023.06.08.00" in the fbthrift part

Thank you for your help! This problem seems to have been solved without modifying  contrib/update-submodules.sh. executing git clone over again just work.
