### ISSUE TITLE
Create a version with stable facebook project dependencies

### ISSUE THREAD

**Issue by wangyuyue** [facebook/CacheLib#260]
**Is your feature request related to a problem? Please describe.**
Cachelib is a great project, but as I have been using it for some days, I find it fails to build over and over again. Most of the time, the build error is caused by the frequent synchronizations with the latest project dependencies, especially those developed inside Facebook, such as folly. They are excellent, but as they are not built specifically for Cachelib, sometimes conflicts happen.

**Describe the solution you'd like**
I suggest that Cachelib should have a stable version, whose submodule dependencies point to external repo **tags** stable for the Cachelib project.

I expect this would greatly reduce frustration during the project-building procedure, and we will see fewer build-failure related issues, sparing more time and space for constructive discussions and contributions.

**Comment by jaesoo-fb** [comment]
@wangyuyue  Hi. Thanks for the suggestion. 

Yeah, we are aware of this issue and we have been discussing internally about this issue. 

And as you suggested, we are going to publish the stable version regularly and share here https://github.com/facebook/CacheLib/releases. 

For now, all of the build issues should have been resolved and we just published the first release there. Please check it out.

Thanks.
