### ISSUE TITLE
Build failure - cannot find python-six

### ISSUE THREAD

**Issue by MHamour** [facebook/CacheLib#269]
Building on Fedora, and the build fails as it can't find python-six package. 

> CMake Warning at CMakeLists.txt:122 (find_package):
>   By not providing "Findpython-six.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "python-six", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "python-six" with
>   any of the following names:
> 
>     python-sixConfig.cmake
>     python-six-config.cmake
> 
>   Add the installation prefix of "python-six" to CMAKE_PREFIX_PATH or set
>   "python-six_DIR" to a directory containing one of the above files.  If
>   "python-six" provides a separate development package or SDK, be sure it has
>   been installed.
> 

I tried the direct build, but can't seem to get it to recognize the path. I also see that the same failure is reported on Ubuntu builds. Any direction on what's needed in terms of build steps to work around this?

**Comment by jaesoo-fb** [comment]
Hi @MHamour Is this issue also for fedora38? https://github.com/facebook/CacheLib/issues/272

**Comment by MHamour** [comment]
Yes, this was on Fedora 38. I started from a fresh image and reinstalled all dependencies and it now works.
