### ISSUE TITLE
New runtime error

### ISSUE THREAD

**Issue by wangyuyue** [facebook/CacheLib#273]
## Describe the bug

Runtime error

## To Reproduce

git clone https://github.com/facebook/CacheLib
cd CacheLib
./contrib/build.sh -T -j
cd examples/simple_cache
./build.sh
./build/simple-cache-example
### Expected behavior
Run example program successfully

### Output

ERROR: flag 'logtostderr' was defined more than once (in files '/users/glacier/work/CacheLib/cachelib/external/glog/src/logging.cc' and 'src/logging.cc').

## Desktop:

OS: Ubuntu 20.04

**Comment by jaesoo-fb** [comment]
Hi @wangyuyue 

It looks like the build is OK for Ubuntu 20.04 in docker.

```
root@docker-desktop:/opt/workspace/examples/simple_cache# uname -a
Linux docker-desktop 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
root@docker-desktop:/opt/workspace/examples/simple_cache# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
root@docker-desktop:/opt/workspace/examples/simple_cache# build/simple-cache-example
root@docker-desktop:/opt/workspace/examples/simple_cache#
```
I used the latest tag v20231101_RC1

**Comment by wangyuyue** [comment]
Hi @jaesoo-fb, I tried this tag. It fails to build fbthrift dependency.

**Comment by wangyuyue** [comment]
> Hi @wangyuyue
> 
> It looks like the build is OK for Ubuntu 20.04 in docker.
> 
> ```
> root@docker-desktop:/opt/workspace/examples/simple_cache# uname -a
> Linux docker-desktop 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
> root@docker-desktop:/opt/workspace/examples/simple_cache# cat /etc/lsb-release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=20.04
> DISTRIB_CODENAME=focal
> DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
> root@docker-desktop:/opt/workspace/examples/simple_cache# build/simple-cache-example
> root@docker-desktop:/opt/workspace/examples/simple_cache#
> ```
> 
> I used the latest tag v20231101_RC1

And the build is indeed ok. It's the runtime error that troubles me. It seems that the glog is linked several times.

**Comment by jaesoo-fb** [comment]
Yeah, I confirmed the simple cache (`build/simple-cache-example`) runs fine. Could you rebuild and retry?

**Comment by wangyuyue** [comment]
After reading #51 , #147 , and #190 , I think it is a long-existing error.
Is it possible to resolve this in the main branch? Thanks.
