### ISSUE TITLE
cachelib fails to build

### ISSUE THREAD

**Issue by george-reilly-wdc** [facebook/CacheLib#275]
**Describe the bug**
(build.sh: error: failed to build cachelib)

**To Reproduce**
1.  git clone https://github.com/facebook/CacheLib
2. cd CacheLib/
3. ./contrib/build.sh -j
4. See error in Screenshots section

**Expected behavior**
successful build

**Screenshots**
[ 81%] Building CXX object allocator/CMakeFiles/cachelib_allocator.dir/SlabReleaseStats.cpp.o
[ 82%] Building CXX object allocator/CMakeFiles/cachelib_allocator.dir/TempShmMapping.cpp.o
/tmp/cciWu1Ct.s: Assembler messages:
/tmp/cciWu1Ct.s:5: Warning: setting incorrect section attributes for .rodata.thrift.data
/tmp/ccVWjB2C.s: Assembler messages:
/tmp/ccVWjB2C.s:5: Warning: setting incorrect section attributes for .rodata.thrift.data
/tmp/ccQo6GYZ.s: Assembler messages:
/tmp/ccQo6GYZ.s:5: Warning: setting incorrect section attributes for .rodata.thrift.data
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [allocator/CMakeFiles/cachelib_allocator.dir/build.make:397: allocator/CMakeFiles/cachelib_allocator.dir/CacheAllocator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:532: allocator/CMakeFiles/cachelib_allocator.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
build-package.sh: error: make failed
build.sh: error: failed to build cachelib

**Desktop (please complete the following information):**
 - OS:
 # uname -a
Linux fb-yv3-w05 5.12.0-0_fbk2_3390_g7ecb4ac46d7f #1 SMP Tue Dec 14 10:55:56 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/redhat-release
CentOS Stream release 8

**Additional context**
N/A

**Comment by jaesoo-fb** [comment]
Hi @george-reilly-wdc Our Centos 8.1 build is green https://github.com/facebook/CacheLib/blob/main/.github/workflows/build-cachelib-centos-8-1.yml

Could you try on Centos 8.1 or 8.5?

**Comment by george-reilly-wdc** [comment]
Yes, I will build a centos-8-1 system and retry. Not sure when I will get around to doing that. Please close this ticket. Thanks.

**Comment by george-reilly-wdc** [comment]
Can we re-open this ticket or should I submit a new one? 
Environment : 
[root@fb-yv3-s1-n1 /]# uname -a
Linux fb-yv3-s1-n1 5.12.0-0_fbk2_3390_g7ecb4ac46d7f #1 SMP Tue Dec 14 10:55:56 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@fb-yv3-s1-n1 /]# cat /etc/redhat-release
CentOS Linux release 8.1.1911 (Core)

Command :  git clone https://github.com/facebook/CacheLib.git
Fails with : 
[ 82%] Building CXX object allocator/CMakeFiles/cachelib_allocator.dir/PoolRebalancer.cpp.o
/tmp/ccyAQXIu.s: Assembler messages:
/tmp/ccyAQXIu.s:5: Warning: setting incorrect section attributes for .rodata.thrift.data
/tmp/ccojqa91.s: Assembler messages:
/tmp/ccojqa91.s:5: Warning: setting incorrect section attributes for .rodata.thrift.data
/tmp/ccOLUSsf.s: Assembler messages:
/tmp/ccOLUSsf.s:5: Warning: setting incorrect section attributes for .rodata.thrift.data
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [allocator/CMakeFiles/cachelib_allocator.dir/build.make:397: allocator/CMakeFiles/cachelib_allocator.dir/CacheAllocator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:532: allocator/CMakeFiles/cachelib_allocator.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
build-package.sh: error: make failed
build.sh: error: failed to build cachelib

Then I tried using the link you gave above with this command : 
git clone https://github.com/facebook/CacheLib/blob/main/.github/workflows/build-cachelib-centos-8-1.yml
And it failed with : 
[root@fb-yv3-s1-n1 /]# git clone https://github.com/facebook/CacheLib/blob/main/.github/workflows/build-cachelib-centos-8-1.yml
Cloning into 'build-cachelib-centos-8-1.yml'...
fatal: repository 'https://github.com/facebook/CacheLib/blob/main/.github/workflows/build-cachelib-centos-8-1.yml/' not found
