### ISSUE TITLE
Where is `cachelib/facebook/admin/CacheAdmin.h`?

### ISSUE THREAD

**Issue by seekstar** [facebook/CacheLib#278]
I want to use `facebook::rocks_secondary_cache::RocksCachelibWrapper` in my project. However, after including `cachelib/adaptor/rocks_secondary_cache/CachelibWrapper.h`, the compiler complains that `cachelib/facebook/admin/CacheAdmin.h` is not found. I can't find the header in the cachelib repo, either. I even tried to google the file, but still can't find it.

**Comment by seekstar** [comment]
It seems that it's a private header file for internal use in facebook. I copied RocksCachelibWrapper-related code to a separate repo with internally used code removed, so that it can compile normally: <https://github.com/seekstar/RocksCachelibWrapper>

**Comment by gaowayne** [comment]
great work!~ @seekstar buddy, did you implement one rocksdb sencondary cache that is on top cache lib already? can you point to me? :)
