### ISSUE TITLE
invalid allocationClassSizeFactor

### ISSUE THREAD

**Issue by tangliisu** [facebook/CacheLib#30]
When I test cachelib in a test cluster, an error is thrown
`E0818 21:25:01.105298    14 cachelib_cache_handler.cpp:54] invalid factor 6.93298464824273e-310
`
it throws from the check from MemoryAllocator.cpp
`generateAllocSizes {
  if (factor <= 1.0) {
    throw std::invalid_argument(folly::sformat("invalid factor {}", factor));
  }
}`

The way i create cachelib instance is
```
    Cache::Config config;
    config.setCacheSize(cache_size).setCacheName(cache_name).validate();
    return std::make_unique<Cache>(config);
```
where cache_size = 76GB.

I didn't set allocationClassSizeFactor anywhere and i think it is defaulted as 1.25? I am not sure what this config (allocationClassSizeFactor) is and why it is 0.

**Comment by tangliisu** [comment]
Hi @sathyaphoenix finally we find the root cause is we set -DFOLLY_SSE=0 to support AVX512 compiler optimizer. But cachelib requires folly::dynamic and f14map in nvmconfig and f14map requires at least FOLLY_SSE=2. I think cachelib does not check this case but just throws an error with a confusing error message.

Do you think we can add an additional check or have a comment in nvmconfig to avoid this issue?

**Comment by sathyaphoenix** [comment]
@tangliisu Can you share the confusing error message that you see and also more details on how this causes the double value to be ~0. Also, please note that NvmConfig has moved away from using folly::dynamic in the main branch and it  has simple declarative api to configure it. https://cachelib.org/docs/Cache_Library_User_Guides/Configure_HybridCache) .. We do rely on F14Map though. Once you share the error message, we can look into an appropriate work around.

**Comment by tangliisu** [comment]
Thanks for the info. We pin cachelib to an old version so nvmconfig is still there.

I could not reproduce the error message allocationClassFSizeFactor ~0 in recent build. Recently the bad build error stack trace is
```
F0902 20:10:39.052548    14 dynamic.cpp:137] Check failed: 0 
*** Check failure stack trace: ***
    @     0x7f8d2b6739bd  google::LogMessage::Fail()
    @     0x7f8d2b6758a8  google::LogMessage::SendToLog()
    @     0x7f8d2b673563  google::LogMessage::Flush()
    @     0x7f8d2b6762f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8d2b0ce716  folly::dynamic::operator=()
    @     0x562fb47e392e  facebook::cachelib::NvmCache<>::Config::Config()
    @     0x562fb47ed0b3  facebook::cachelib::CacheAllocatorConfig<>::CacheAllocatorConfig()
    @     0x562fb483b122  facebook::cachelib::CacheAllocator<>::CacheAllocator()
    @     0x562fade7cb2a  cache_util::CreateCachelib()
    @     0x562fade80c32  cache_util::CachelibCacheHandler::CachelibCacheHandler()
    @     0x562fadc40b48  scorpion::CreateCacheHandler()
    @     0x562fad98330c  CreateScorpionHandlerV2()
    @     0x562fad7853b8  main
    @     0x7f8d1aa53bf7  (unknown)
    @     0x562fad97b61a  _start
```
which makes sense. But i happened to get the ~0 error before we figured out the FOLLY_SSE=0 issue
```
E0818 21:25:01.129964    14 ExceptionTracer.cpp:214] exception stack complete
terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid factor 6.93298464824273e-310
```

If cachelib still rely on F14Map, i guess we need to have FOLLY_SSE=2.

BTW we implemented cachelib in our system. The perf is very impressive. We are still working on tuning the cachelib to see if we could further reduce the CPU usage.

**Comment by sathyaphoenix** [comment]
Great to hear it is working out as expected. Let us know if you need any information for tuning. 

It is strange though that not setting FOLLY_SSE=2 would cause an unrelated double to be broken. cc @agordon  if he has any insights to share.
