### ISSUE TITLE
build failed when building dependency 'fbthrift'

### ISSUE THREAD

**Issue by pyynb** [facebook/CacheLib#317]
hi cachelib team, I just encountered an error while building cachelib,

[ 24%] Linking CXX executable ../../bin/thrift1
cd /home/ubuntu/cachelib/CacheLib/build-fbthrift/thrift/compiler && /opt/conda/envs/gpu/lib/python3.10/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/thrift1.dir/link.txt --verbose=YES
/usr/bin/c++ -g -rdynamic CMakeFiles/thrift1.dir/main.cc.o CMakeFiles/thrift1.dir/compiler.cc.o -o ../../bin/thrift1  -Wl,-rpath,/home/ubuntu/cachelib/CacheLib/build-fbthrift/lib:/home/ubuntu/cachelib/CacheLib/opt/cachelib/lib: ../../lib/libcompiler_base.a -Wl,--whole-archive ../../lib/libcompiler_generators.a -Wl,--no-whole-archive ../../lib/libcompiler_base.a ../../lib/libcompiler.so.1.0.0 ../../lib/libcompiler_ast.so.1.0.0 -lssl -lcrypto /home/ubuntu/cachelib/CacheLib/opt/cachelib/lib/libfmtd.so.10.2.1 ../../lib/libmustache.so.1.0.0
/usr/bin/ld: ../../lib/libcompiler_generators.a(t_mstch_python_capi_generator.cc.o): in function `apache::thrift::compiler::(anonymous namespace)::format_marshal_type_unadapted(apache::thrift::compiler::t_node const&, std::basic_string_view<char, std::char_traits<char> >)':
/home/ubuntu/cachelib/CacheLib/cachelib/external/fbthrift/thrift/compiler/generate/t_mstch_python_capi_generator.cc:235: undefined reference to `apache::thrift::compiler::is_type_iobuf(std::basic_string_view<char, std::char_traits<char> >)'
/usr/bin/ld: ../../lib/libcompiler_generators.a(t_mstch_python_capi_generator.cc.o): in function `apache::thrift::compiler::(anonymous namespace)::python_capi_mstch_struct::eligible_type_override(apache::thrift::compiler::t_const const*)':
/home/ubuntu/cachelib/CacheLib/cachelib/external/fbthrift/thrift/compiler/generate/t_mstch_python_capi_generator.cc:473: undefined reference to `apache::thrift::compiler::is_type_iobuf(std::basic_string_view<char, std::char_traits<char> >)'
/usr/bin/ld: ../../lib/libcompiler_generators.a(t_mstch_python_capi_generator.cc.o): in function `apache::thrift::compiler::(anonymous namespace)::python_capi_mstch_struct::eligible_type_or_adapter_override(apache::thrift::compiler::t_type const*)':
/home/ubuntu/cachelib/CacheLib/cachelib/external/fbthrift/thrift/compiler/generate/t_mstch_python_capi_generator.cc:500: undefined reference to `apache::thrift::compiler::is_type_iobuf(std::basic_string_view<char, std::char_traits<char> >)'
/usr/bin/ld: ../../lib/libcompiler_generators.a(t_mstch_python_generator.cc.o): in function `apache::thrift::compiler::(anonymous namespace)::python_mstch_type::is_iobuf()':
/home/ubuntu/cachelib/CacheLib/cachelib/external/fbthrift/thrift/compiler/generate/t_mstch_python_generator.cc:656: undefined reference to `apache::thrift::compiler::is_type_iobuf(apache::thrift::compiler::t_type const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [thrift/compiler/CMakeFiles/thrift1.dir/build.make:122: bin/thrift1] Error 1
make[2]: Leaving directory '/home/ubuntu/cachelib/CacheLib/build-fbthrift'
make[1]: *** [CMakeFiles/Makefile2:393: thrift/compiler/CMakeFiles/thrift1.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/cachelib/CacheLib/build-fbthrift'
make: *** [Makefile:156: all] Error 2
build-package.sh: error: make failed
build.sh: error: failed to build dependency 'fbthrift'

how should I fix this? thank you

**Comment by Maizesty** [comment]
I have the same problem. My solution is reset the commit of fbthrift to 15433ba2.
我前几天也是因为fbthrift导致build失败了，我的解决方法是找到fbthrift这个子模块，并且把他的提交记录回退到了15433ba2。

**Comment by therealgymmy** [comment]
Yes our builds have been broken for the past month due to numerous dependency issues (fbthrift was one of them). For now, the suggestion is to roll back each broken dependency's commit to an earlier time and see if builds work.

We're still working with internal teams to ensure our FB dependencies become healthy again.

**Comment by therealgymmy** [comment]
thrift should have been fixed by now
