### ISSUE TITLE
Question: how cachelib recover cache by its metadata

### ISSUE THREAD

**Issue by tangliisu** [facebook/CacheLib#32]
When cachelib backups metadata during shutdown, it seems the size of metadata is quite small. Why can cachelib recover the whole cache based on the small size of metadata? Could you introduce more idea on the metadata and its recovery?

**Comment by sathyaphoenix** [comment]
@tangliisu That's the next target for the team. We are figuring out the process of polishing the internal docs and transferring them to the website. Stay tuned.

**Comment by tangliisu** [comment]
@sathyaphoenix thank you! i figure out this question by going through the shm code. But some docs would be super helpful. Please feel free to closing this ticket.
