### ISSUE TITLE
Build issue with CacheLib with missing source files

### ISSUE THREAD

**Issue by sairahul-chalamalasetti** [facebook/CacheLib#320]
**Describe the bug**
While building cachelib on Ubuntu 22.04 and kernel 6.7.0-060700-generic got errors for missing source files from benchmarks folder
. **To Reproduce**
During build instructions provided at [
](https://cachelib.org/docs/installation/)
 ./contrib/build.sh -j -T

**Expected behavior**
Get CMAKE Error

-- Configuring done
CMake Error at CMakeLists.txt:134 (add_executable):
  Cannot find source file:

    BinarySearchVsHashTableBench.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:38 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  Cannot find source file:

    CachelibMapOperationBench.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:41 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  Cannot find source file:

    CachelibMapWorkloadBench.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:42 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  Cannot find source file:

    CachelibRangeMapWorkloadBench.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:43 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  No SOURCES given to target: benchmark-test-BinarySearchVsHashTableBench
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:38 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  No SOURCES given to target: benchmark-test-CachelibMapOperationBench
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:41 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  No SOURCES given to target: benchmark-test-CachelibMapWorkloadBench
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:42 (add_test)

CMake Error at CMakeLists.txt:134 (add_executable):
  No SOURCES given to target: benchmark-test-CachelibRangeMapWorkloadBench
Call Stack (most recent call first):
  benchmarks/CMakeLists.txt:34 (generic_add_test)
  benchmarks/CMakeLists.txt:43 (add_test)

CMake Generate step failed.  Build files cannot be regenerated correctly.
build-package.sh: error: cmake failed on cachelib
build.sh: error: failed to build cachelib

**Comment by therealgymmy** [comment]
@sairahul-chalamalasetti Hi, can you check if the builds work for you now?

**Comment by sairahul-chalamalasetti** [comment]
The build works now. Thanks for fixing it !!
