### ISSUE TITLE
Are there instructions on how to build and install in Amazon Linux?

### ISSUE THREAD

**Issue by srgsanky** [facebook/CacheLib#331]
I tried the following commands mentioned in the Installation wiki

```bash
git clone https://github.com/facebook/CacheLib
cd CacheLib

./contrib/build.sh -d -j
```

but this throws the error

```
build.sh: error: No build recipe for detected operating system 'amzn2'
```

Instead, I tried to pull the submodules and build using the `-O` flag to skip OS package installation

```bash
./contrib/update-submodules.sh
./contrib/build.sh -d -j -O -S
```

This throws multiple warnings in `find_library` of CMake and eventually fails the build due to missing some library.

```
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LIBURING)
  does not match the name of the calling package (LibUring).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMake/FindLibUring.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMake/folly-deps.cmake:139 (find_package)
  CMakeLists.txt:133 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

The number of dependencies and the build errors are overwhelming for me. If there are instructions to get started on CacheLib without having to fight the build, it will be really helpful. Also are there binaries hosted anywhere that I can use directly?

**Comment by pbhandar2** [comment]
We do not support Amazon Linux. Please use an OS we support: Ubuntu 22.04, CentOS 9 and Rocky Linux 9.
