### ISSUE TITLE
Samples get linked with system glog.so and glogd.so built from source resulting in conflicts

### ISSUE THREAD

**Issue by vicvicg** [facebook/CacheLib#51]
Samples from ./examples/[simple_cache|simple_compact_cache] get linked with system glog.so and glogd.so built from source resulting in conflicts.

Steps to reproduce:
> ./contrib/build.sh -d -v # Build CacheLib
> cd examples/simple_cache/
> ./build.sh # Build simple_cache example
> ldd build/simple-cache-example | grep glog
        libglog.so.0 => /lib/x86_64-linux-gnu/libglog.so.0 (0x00007f0d95bae000)
        libglogd.so.0 => /home/<reduct>/CacheLib/opt/cachelib/lib/libglogd.so.0 (0x00007f0d941ef000)
> ./build/simple-cache-example
**ERROR**: flag 'logtostderr' was defined more than once (in files '/home/<reduct>/CacheLib/cachelib/external/glog/src/logging.cc' and 'src/logging.cc').

OS: Ubuntu 20.04 running on WSL2.

**Comment by decibel26** [comment]
Getting the same error. I tried on a new VM Ubuntu 20.04.3 LTS, still getting the error.
ERROR: flag 'logtostderr' was defined more than once (in files '/home/student/CacheLib/cachelib/external/glog/src/logging.cc' and 'src/logging.cc').

**Comment by agordon** [comment]
Thank you @vicvicg and @decibel26 - you stumbled on an edge case - building "cachelib" in debug mode (`build.sh -d`) and the sample in release mode (the default of the `build.sh` script).
I'll commit a fix that allows building the sample in debug mode as well.
As a temporary work-around, please try adding `-DCMAKE_BUILD_TYPE=Debug` to the `CMAKE_PARAMS` in line 28 of:
https://github.com/facebook/CacheLib/blob/f200cefa6795e250fef535a5b026c8b6b6ac84a7/examples/simple_cache/build.sh#L28

**Comment by vicvicg** [comment]
> -DCMAKE_BUILD_TYPE=Debug

Thank you, @agordon - this workaround works.

**Comment by sathyaphoenix** [comment]
Thanks for the quick work-around @agordon !

**Comment by decibel26** [comment]
Worked for me as well. Thanks, @agordon.

**Comment by sathyaphoenix** [comment]
@vicvicg  Is this still an issue for you ?

**Comment by vicvicg** [comment]
@sathyaphoenix What is the recommended way to switch between release and debug builds for samples without modifying the build file itself?

**Comment by sathyaphoenix** [comment]
@agordon  is the fix that you mention committed  to main branch ?
