### ISSUE TITLE
no resetToHandle found. 

### ISSUE THREAD

**Issue by zzerroo** [facebook/CacheLib#65]
# Summary of Issue or Feature request
the function resetToItemHandle in FixedSizeArray.h calls  resetToHandle, but there is no such function in this project。Should it be resetToItemHandle (in TypedHandle.h) ？

## Goal
Should it be resetToItemHandle (in TypedHandle.h)  ？

**Comment by sathyaphoenix** [comment]
@zzerroo  you are right! Do you mind sending out a PR to fix this. Also, could you share some context on how you plan to use the FixedSizeArray.

**Comment by zzerroo** [comment]
ok, i will send out a pr later. currently we are just doing some simple encapsulation.

**Comment by sathyaphoenix** [comment]
This is now fixed. Thanks @zzerroo
