### ISSUE TITLE
An typo in CacheLib docs

### ISSUE THREAD

**Issue by skyelves** [facebook/CacheLib#71]
There is an typo in https://cachelib.org/docs/Cache_Library_User_Guides/Write_data_to_cache#write-data-to-allocated-memory-and-insert-item-handle-into-cache.
```
string data("new data");
// Allocate memory for the data.
auto item_handle = cache->allocate(pool_id, "key2", data.size());

// Write the data to the cache.
std::memcpy(handle->getMemory(), data.data(), data.size());
```
There is no `handle` but `item_handle`. Therefore, `std::memcpy(handle->getMemory(), data.data(), data.size());` should be changed to `std::memcpy(item_handle->getMemory(), data.data(), data.size());`

**Comment by haowu14** [comment]
Thank you for pointing out! Fix is on the way.

**Comment by haowu14** [comment]
Finally redeployed webpage.
