### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by vitruvvius** [facebook/CacheLib#74]
Hey there!

I was wondering what the current story around replication happens to be so that one can survive in the midst of failure / higher availability + total throughput - building a prototype of a highly concurrent service.... would require ~30 node cluster assuming a direct port from redis (although, from experimentation, cachelib will have less memory footprint)

**Comment by vitruvvius** [comment]
in more detail, running a service that's the equivalent of a game engine directly on envoy proxy by hooking into their underlying APIs

to store the session data + user device information and enable a global MPI, we need a high performant cache. of course, cachelib was the first thought that came to mind. but, i haven't been able to find native support for replication...

**Comment by haowu14** [comment]
It is correct that CacheLib does not support replication natively. 
It's also worth noting that CacheLib will only be able to persist its cache content across restarts if cacheAllocator::shutDown() is called appropriately.
