### ISSUE TITLE
How to configure caching using NVMe only？

### ISSUE THREAD

**Issue by xiedeyantu** [facebook/CacheLib#80]
I don't want to use memory, or use a small memory configuration. How to use cachebench for configuration and pressure measurement？Could you give me some advice.

**Comment by leozzx** [comment]
Cachelib doesn't support NVM cache only, you have to specify at least a small portion of DRAM memory.
Can I know why you don't want to use a small memory?

**Comment by xiedeyantu** [comment]
> Cachelib doesn't support NVM cache only, you have to specify at least a small portion of DRAM memory. Can I know why you don't want to use a small memory?

I know that cachelib realizes the seamless connection between DRAM and SSD cache. I want to mainly use SSD cache because cachelib optimizes SSD a lot. For example, if I configure 1T SSD, the size of key is 1024 bytes and the size of value is 1MB. What is the recommended minimum memory?

**Comment by leozzx** [comment]
> > Cachelib doesn't support NVM cache only, you have to specify at least a small portion of DRAM memory. Can I know why you don't want to use a small memory?
> 
> I know that cachelib realizes the seamless connection between DRAM and SSD cache. I want to mainly use SSD cache because cachelib optimizes SSD a lot. For example, if I configure 1T SSD, the size of key is 1024 bytes and the size of value is 1MB. What is the recommended minimum memory?

I would say at least 10MB, because we have 4MB for a slab + other overhead. But it might not be the best config, you can try it out with our Cachebench tool.
Just FYI, we have a very similar internal use case that treats us as SSD cache, they configs 256MB for DRAM cache.

**Comment by xiedeyantu** [comment]
thanks!
