### ISSUE TITLE
Is BigHash.Bucket.Slot.Size and BlockCache.Region.Entry.EntryDesc.KeyHash do not need serialize to disk.

### ISSUE THREAD

**Issue by SwordHoly** [facebook/CacheLib#82]
![BigHashSlotSize](https://user-images.githubusercontent.com/2174770/143409090-66e68f70-bfad-46f9-84e3-e0eb38477b9c.jpg)
![BlockCacheSize](https://user-images.githubusercontent.com/2174770/143409142-a82e2c8f-4e46-4fb7-ad1a-b9002f6bec25.jpg)
As upper pictures shows,  BigHash.Bucket.Slot.Size can be calculated by Slot.BucketEntry.KeySize + Slot.BucketEntry.ValueSize,  BlockCache.Region.Entry.EntryDesc.KeyHash can be calculated from BlockCache.Region.Entry.EntryValue.Key. So I think it's do not  need to serialize BigHash.Bucket.Slot.Size  and  BlockCache.Region.Entry.EntryDesc.KeyHash,  and can save disk space.  Especially BigHash is for smallItem, maybe KeySize and ValueSize is jiust 1 byte, the 4 bytes size overhead is not small.

**Comment by sunnyszy** [comment]
BTW @SwordHoly the slides look very nice. Can you share the full version? I could not find them by search.

**Comment by leozzx** [comment]
I think this is to reduce the cpu cost during lookup, the disk space is not a top constraint comparing to cpu and memory.
Adding up to you, there's also an 8 bytes keyHash inside the BucketEntry.

**Comment by SwordHoly** [comment]
> I think this is to reduce the cpu cost during lookup, the disk space is not a top constraint comparing to cpu and memory. Adding up to you, there's also an 8 bytes keyHash inside the BucketEntry.

Thanks for replay, i think cpu cost for calucate SlotSize from KeySize and ValueSize is also very small, maybe cachelib do this is just for code hierarchy
