### ISSUE TITLE
What is the relationship between popularityWeights, popularityBuckets and htBucketPower

### ISSUE THREAD

**Issue by xiedeyantu** [facebook/CacheLib#83]
I know that htbucketpower is the number of buckets to the nth power of 2. Popularityweights and popularitybuckets play a role in the cachebench. Could you tell me more detail please？

**Comment by xiedeyantu** [comment]
by the way, can not valSize be greater than 4MB? I use configuration: "valSizeRange": [ 5242880,5242882 ] and "enableChainedItem": true to test navy, set       :    16,156/s, success   :   0.00%

**Comment by leozzx** [comment]
> by the way, can not valSize be greater than 4MB? I use configuration: "valSizeRange": [ 5242880,5242882 ] and "enableChainedItem": true to test navy, set : 16,156/s, success : 0.00%

valSize can't be greater than 4MB, Cachebench doesn't automatically split the item into chained items. You should use "chainedItemValSizeRange" to specify chained item size.

**Comment by sathyaphoenix** [comment]
@xiedeyantu  chained items stress test was  implemented in cachebench much later. Like @leozzx  pointed out, the chainedItemValSizeRange and chainedItemLengthRange and chainedItemLengthRangeProbability control how long the values are including the chain. We are missing documentation on this in https://cachelib.org/docs/Cache_Library_User_Guides/Configuring_cachebench_parameters 

@leozzx  we should document the chained item length parameters here in our next documentation sprint.
