### ISSUE TITLE
Any plan to support cross platform like ubuntu20.04 centos 7 and OSX?

### ISSUE THREAD

**Issue by hudengjunai** [facebook/CacheLib#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agordon** [comment]
Hello,
Ubuntu and CentOS should "just work", please report back if you are experiencing problems.
Mac OS (which is, btw, no longer "X" as it moved beyond version 10) - is currently being worked on.

**Comment by therealgymmy** [comment]
Closing as these platforms are supported now.
