### ISSUE TITLE
Build error "CacheStats.cpp:51:33: error: conversion from ‘SizeVerify<15968>’ to non-scalar type ‘SizeVerify<16160>’ requested"

### ISSUE THREAD

**Issue by wenhaocs** [facebook/CacheLib#88]
**Describe the bug**
Tried to build cachelib on ubuntu:18.04, ubuntu:latest, and centos:8 docker container, running on Mac M1 MacOS 12. But all failed with error "CacheStats.cpp:51:33: error: conversion from ‘SizeVerify<15968>’ to non-scalar type ‘SizeVerify<16160>’ requested".

**To Reproduce**
1. docker run -it centos:8 /bin/bash
2. inside container clone cachelib repo
3. ./contrib/build.sh -j

**Screenshots**
![image](https://user-images.githubusercontent.com/19355821/144689399-63de18cf-4c6d-4931-8dff-7d9f501e918e.png)

**Desktop (please complete the following information):**
 - Macbook M1
 - Docker version 20.10.10
 - OS: [MacOS 12.0.1]
 - Docker image: ubuntu:18.04, ubuntu:latest, and centos:8

**Comment by sathyaphoenix** [comment]
@wenhaocs The MacOS build is not yet ready. @agordon  is working on it and expect to hear some updates from him soon. The list of supported platforms for the current build script is listed here https://cachelib.org/docs/installation/installation#build-script

**Comment by wenhaocs** [comment]
Thank you!

**Comment by wenhaocs** [comment]
Hi @agordon , can I check how is the support of CacheLib on ARM?

**Comment by agordon** [comment]
Hi,
Jut to verify - we have a working solution for building directly on MacOS/M1 - but you are building on Linux/M1 (Ubuntu with docker) ?
While I haven't checked this scenario directly, I believe the following patch can solve this specific compilation issue:
https://github.com/agordon/CacheLib/commit/8f1eb626ba13893c606959ee28289b5de6a174fb
(this will be merged into mainline soon, after few more tests).

Can you try this?

**Comment by wenhaocs** [comment]
Hi @agordon, actually we are more concerned about the compatibility with general ARM architecture (Linux, M1, etc.). (sorry about the confusion of asking under this thread). If I understand correctly, this patch will fix the M1 issue right?
