### ISSUE TITLE
Build on centos8 failed

### ISSUE THREAD

**Issue by xiedeyantu** [facebook/CacheLib#89]
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `X509_STORE_CTX_get_chain'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `sk_pop_free'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `SSL_CTX_get_ex_new_index'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `SSL_load_error_strings'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `EVP_cleanup'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_set_dynlock_lock_callback'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `sk_num'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `sk_value'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_THREADID_set_callback'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_add_lock'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_cleanup_all_ex_data'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `SSL_get_ex_new_index'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `HMAC_CTX_cleanup'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `HMAC_CTX_init'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `EVP_MD_CTX_cleanup'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `OpenSSL_add_all_ciphers'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `SSLv23_method'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `OpenSSL_add_all_digests'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_set_dynlock_destroy_callback'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `ERR_free_strings'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `EVP_MD_CTX_init'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `SSL_library_init'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_THREADID_set_numeric'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_set_dynlock_create_callback'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `ERR_load_crypto_strings'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_set_locking_callback'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../../../libfolly.so.0.58.0-dev: undefined reference to `CRYPTO_num_locks'
collect2: error: ld returned 1 exit status
make[2]: *** [folly/logging/example/CMakeFiles/logging_example.dir/build.make:126: folly/logging/example/logging_example] Error 1
make[2]: Leaving directory '/code/CacheLib/build-folly'
make[1]: *** [CMakeFiles/Makefile2:357: folly/logging/example/CMakeFiles/logging_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by SwordHoly** [comment]
Maybe folly version is too old, I can complie  success with folly version v2021.03.01.00
