### ISSUE TITLE
cross-platform install integeraged to vcpkg

### ISSUE THREAD

**Issue by hudengjunai** [facebook/CacheLib#90]
Thank you for this excellent work. I  have read the docs of CacheLib, and want to use as In-process mutithread read-write cache. But I failed install on macos and centos7 system. 
Can you give a vcpkg cross-platform install solution?

**Comment by Pospelove** [comment]
@hudengjunai now there is a vcpkg port https://github.com/microsoft/vcpkg/pull/29973/files
but linux only for now
